version: '3.5'
services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - BASE_URL=http://localhost:3000
      - TZ=Africa/Tunis
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gateway?schema=public
      - JWT_SECRET=super-secret
      - CLIENT_URL=http://localhost:3000
      - CLIENT_DOMAIN=localhost
    entrypoint: /app/entrypoint.sh
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
  
  prisma-studio:
    container_name: prisma-studio
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5555:5555
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: npx prisma studio

  postgres:
    image: postgres:14.8
    container_name: postgres
    restart: unless-stopped
    # user: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=gateway
      - POSTGRES_DB=gateway
    volumes:
      - postgres-gateway:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9090:8080
    restart: unless-stopped
volumes:
  postgres-gateway: